/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters extends org.apache.shiro.cas.grails.ShiroCasSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                if (controllerName == "assets") return true
                if (controllerName == "public") return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
